"""
Research-grade report generation (PDF + consolidated Excel).

GAP-009: Complete PDF report with structured sections.
GAP-011: One Excel workbook with multiple worksheets.
GAP-012: Embedded plots in Excel worksheets.
GAP-013: README/Configuration/Reproducibility sheets.

Dependencies:
  - openpyxl (Excel): pip install openpyxl
  - matplotlib (plots for embedding)
  - reportlab or fpdf2 (PDF): pip install fpdf2
"""

from __future__ import annotations

import io
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger("nanobio.utils.reporting")

# Optional PDF dependency
try:
    from fpdf import FPDF
    _PDF_AVAILABLE = True
except ImportError:
    try:
        from fpdf2 import FPDF
        _PDF_AVAILABLE = True
    except ImportError:
        _PDF_AVAILABLE = False

# Optional Excel image embedding
try:
    from openpyxl.drawing.image import Image as XlImage
    _XL_IMAGE = True
except ImportError:
    _XL_IMAGE = False


class ExcelReportBuilder:
    """Builds a single consolidated Excel workbook.

    Usage:
        builder = ExcelReportBuilder(path)
        builder.add_readme(...)
        builder.add_configuration(...)
        builder.add_signal_metrics(...)
        builder.add_split_info(...)
        builder.add_model_results(...)
        builder.add_qc(...)
        builder.finalize()
    """

    def __init__(self, output_path: Path):
        self.path = Path(output_path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.writer = pd.ExcelWriter(
            self.path, engine="openpyxl",
        )
        self._sheet_count = 0

    def _add_sheet(self, name: str, df: pd.DataFrame,
                   freeze_panes: str = "A2") -> None:
        """Add a DataFrame as a worksheet."""
        sheet_name = name[:31]  # Excel 31-char limit
        df.to_excel(self.writer, sheet_name=sheet_name, index=False)
        ws = self.writer.sheets[sheet_name]
        ws.freeze_panes = freeze_panes
        # Auto-width columns
        for col in ws.columns:
            max_len = max(
                len(str(col[0].value or "")),
                max((len(str(c.value or "")) for c in col), default=0),
            )
            ws.column_dimensions[col[0].column_letter].width = min(max_len + 2, 50)
        self._sheet_count += 1

    def add_readme(self, experiment_id: str, timestamp: str,
                   description: str = "") -> None:
        rows = [
            {"Field": "Experiment ID", "Value": experiment_id},
            {"Field": "Timestamp", "Value": timestamp},
            {"Field": "Description", "Value": description},
            {"Field": "Generated By", "Value": "nanobio pipeline"},
            {"Field": "Report Type", "Value": "Consolidated research workbook"},
        ]
        self._add_sheet("README", pd.DataFrame(rows))

    def add_configuration(self, config_dict: Dict[str, Any]) -> None:
        rows = []
        def _flatten(d, prefix=""):
            for k, v in d.items():
                full_key = f"{prefix}.{k}" if prefix else k
                if isinstance(v, dict):
                    _flatten(v, full_key)
                else:
                    rows.append({"Parameter": full_key, "Value": str(v)})
        _flatten(config_dict)
        self._add_sheet("Configuration", pd.DataFrame(rows))

    def add_dataframe(self, name: str, df: pd.DataFrame) -> None:
        self._add_sheet(name, df)

    def add_split_info(self, split_data: Dict[str, Any]) -> None:
        rows = [{"Field": k, "Value": str(v)} for k, v in split_data.items()]
        self._add_sheet("Data_Split", pd.DataFrame(rows))

    def add_model_results(self, results: List[Dict[str, Any]]) -> None:
        if results:
            self._add_sheet("Model_Performance", pd.DataFrame(results))

    def add_qc_report(self, qc_data: List[Dict[str, Any]]) -> None:
        if qc_data:
            self._add_sheet("Quality_Control", pd.DataFrame(qc_data))

    def add_signal_metrics(self, metrics: Dict[str, Any]) -> None:
        rows = [{"Metric": k, "Value": str(v)} for k, v in metrics.items()]
        self._add_sheet("Signal_Metrics", pd.DataFrame(rows))

    def add_reproducibility(self, env_data: Dict[str, Any]) -> None:
        rows = []
        def _flatten(d, prefix=""):
            for k, v in d.items():
                key = f"{prefix}.{k}" if prefix else k
                if isinstance(v, dict):
                    _flatten(v, key)
                elif isinstance(v, list):
                    rows.append({"Field": key, "Value": str(v)})
                else:
                    rows.append({"Field": key, "Value": str(v)})
        _flatten(env_data)
        self._add_sheet("Reproducibility", pd.DataFrame(rows))

    def embed_plot(self, sheet_name: str, image_path: Path,
                   cell: str = "A1") -> None:
        """GAP-012 FIX: Embed a plot image into an Excel worksheet."""
        if not _XL_IMAGE:
            logger.warning("openpyxl.drawing not available; skipping image embed")
            return
        if not Path(image_path).exists():
            logger.warning("Image not found: %s", image_path)
            return
        try:
            if sheet_name not in self.writer.sheets:
                pd.DataFrame().to_excel(self.writer, sheet_name=sheet_name)
            ws = self.writer.sheets[sheet_name]
            img = XlImage(str(image_path))
            ws.add_image(img, cell)
        except Exception as e:
            logger.warning("Failed to embed image in Excel: %s", e)

    def finalize(self) -> Path:
        self.writer.close()
        logger.info("Excel workbook saved: %s (%d sheets)", self.path, self._sheet_count)
        return self.path


class PDFReportBuilder:
    """Generates a structured research PDF report.

    GAP-009 FIX: Complete PDF with all required sections.
    """

    def __init__(self, output_path: Path, title: str = "Research Report",
                 author: str = ""):
        if not _PDF_AVAILABLE:
            logger.warning("fpdf2 not installed. PDF generation disabled. "
                           "Install with: pip install fpdf2")
            self.enabled = False
            return
        self.enabled = True
        self.path = Path(output_path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.pdf = FPDF()
        self.pdf.set_auto_page_break(auto=True, margin=15)
        self.title = title
        self.author = author

    def _add_title_page(self, experiment_id: str, timestamp: str) -> None:
        self.pdf.add_page()
        self.pdf.set_font("Helvetica", "B", 24)
        self.pdf.cell(0, 60, "", ln=True)
        self.pdf.cell(0, 15, self.title, ln=True, align="C")
        self.pdf.set_font("Helvetica", "", 14)
        self.pdf.cell(0, 10, f"Experiment: {experiment_id}", ln=True, align="C")
        self.pdf.cell(0, 10, f"Date: {timestamp}", ln=True, align="C")
        if self.author:
            self.pdf.cell(0, 10, f"Author: {self.author}", ln=True, align="C")

    def _section(self, title: str, level: int = 1) -> None:
        sizes = {1: 16, 2: 13, 3: 11}
        self.pdf.set_font("Helvetica", "B", sizes.get(level, 11))
        self.pdf.cell(0, 10, title, ln=True)
        self.pdf.set_font("Helvetica", "", 10)

    def _text(self, text: str) -> None:
        self.pdf.multi_cell(0, 5, text)
        self.pdf.ln(3)

    def _table(self, headers: List[str], rows: List[List[str]],
               col_widths: Optional[List[int]] = None) -> None:
        if col_widths is None:
            w = int(190 / max(len(headers), 1))
            col_widths = [w] * len(headers)
        self.pdf.set_font("Helvetica", "B", 9)
        for i, h in enumerate(headers):
            cw = col_widths[i] if i < len(col_widths) else col_widths[-1]
            self.pdf.cell(cw, 7, str(h), border=1)
        self.pdf.ln()
        self.pdf.set_font("Helvetica", "", 8)
        for row in rows:
            for i, val in enumerate(row):
                cw = col_widths[i] if i < len(col_widths) else col_widths[-1]
                self.pdf.cell(cw, 6, str(val)[:50], border=1)
            self.pdf.ln()
        self.pdf.ln(3)

    def add_image(self, image_path: Path, width: int = 170) -> None:
        if not Path(image_path).exists():
            return
        try:
            self.pdf.image(str(image_path), w=width)
            self.pdf.ln(5)
        except Exception as e:
            logger.warning("Failed to add image to PDF: %s", e)

    def build(
        self,
        experiment_id: str,
        timestamp: str,
        config: Dict[str, Any],
        split_info: Dict[str, Any],
        signal_info: Dict[str, Any],
        model_results: List[Dict[str, Any]],
        qc_summary: Dict[str, Any],
        env_info: Dict[str, Any],
        figure_paths: List[Path] = None,
    ) -> Optional[Path]:
        if not self.enabled:
            return None

        self._add_title_page(experiment_id, timestamp)

        # Executive Summary
        self.pdf.add_page()
        self._section("Executive Summary")
        self._text(
            f"This report documents the analysis performed in experiment "
            f"{experiment_id}. The signal processing chain applies "
            f"anti-aliased resampling from {config.get('sampling', {}).get('original_rate_hz', 'N/A')} Hz "
            f"to {config.get('sampling', {}).get('model_input_rate_hz', 'N/A')} Hz, "
            f"followed by a Gaussian LPF at "
            f"{config.get('sampling', {}).get('gaussian_lpf_cutoff_hz', 'N/A')} Hz. "
            f"Data splitting uses stratified file-level assignment."
        )

        # 1. Data Description
        self._section("1. Experimental Data Description")
        if signal_info:
            rows = [[k, str(v)] for k, v in signal_info.items()]
            self._table(["Metric", "Value"], rows, [60, 130])

        # 2. Signal Processing
        self._section("2. Signal Processing Methodology")
        sp = config.get("sampling", {})
        self._text(
            f"Original rate: {sp.get('original_rate_hz', 'N/A')} Hz\n"
            f"Target rate: {sp.get('model_input_rate_hz', 'N/A')} Hz\n"
            f"Anti-aliasing: Butterworth LPF (order {config.get('filters', {}).get('lpf_order', 'N/A')})\n"
            f"Gaussian LPF: {'enabled' if sp.get('gaussian_lpf_enabled', False) else 'disabled'}, "
            f"cutoff = {sp.get('gaussian_lpf_cutoff_hz', 'N/A')} Hz\n"
            f"Cutoff definition: −3 dB point (σ = √ln(2) / (π·f_c))"
        )

        # 3. Data Splitting
        self._section("3. Data Splitting Strategy")
        if split_info:
            rows = [[k, str(v)] for k, v in split_info.items()]
            self._table(["Parameter", "Value"], rows, [70, 120])

        # 4. Model Results
        self._section("4. Model Performance")
        if model_results:
            headers = list(model_results[0].keys())[:6]
            rows = [[str(r.get(h, ""))[:20] for h in headers] for r in model_results]
            w = int(190 / max(len(headers), 1))
            self._table(headers, rows, [w] * len(headers))

        # 5. Quality Control
        self._section("5. Quality Control Summary")
        if qc_summary:
            rows = [[k, str(v)] for k, v in qc_summary.items()]
            self._table(["Check", "Result"], rows, [80, 110])

        # 6. Figures
        if figure_paths:
            self._section("6. Visualizations")
            for fp in figure_paths:
                if Path(fp).exists():
                    self.pdf.add_page()
                    self._text(f"Figure: {Path(fp).stem}")
                    self.add_image(fp)

        # 7. Reproducibility
        self._section("7. Reproducibility")
        if env_info:
            rows = []
            for k, v in env_info.items():
                if not isinstance(v, dict):
                    rows.append([str(k), str(v)])
            if rows:
                self._table(["Parameter", "Value"], rows[:30], [70, 120])

        # 8. Limitations
        self._section("8. Limitations")
        self._text(
            "• Downsampling from 1 MHz to 50 kHz discards frequency content "
            "above 25 kHz. Events shorter than ~40 µs may be unresolvable.\n"
            "• Group-aware splitting is limited by the number of available "
            "device/session groups in the dataset.\n"
            "• Results are from a single train/test split unless cross-validation "
            "is explicitly enabled."
        )

        # 9. Conclusions
        self._section("9. Conclusions")
        if model_results:
            best = max(model_results,
                       key=lambda x: x.get("accuracy", 0) or 0)
            self._text(
                f"Best performing model: {best.get('model', 'N/A')} "
                f"(accuracy={best.get('accuracy', 'N/A')}). "
                f"See detailed per-class metrics in the Excel workbook."
            )

        # Save
        self.pdf.output(str(self.path))
        logger.info("PDF report saved: %s", self.path)
        return self.path